/**
 * Langue de l'app (hors landing). Mémorisée dans un cookie `lang`, posé automatiquement
 * quand l'utilisateur visite /en, et changeable depuis l'app (bouton FR/EN).
 */
export type Lang = "fr" | "en";

/** Libellés de l'app (dashboard, admin, compte). */
export const UI = {
  fr: {
    rules: "Règles", journal: "Journal", account: "Compte", admin: "Admin", signout: "Se déconnecter",
    dashboard: "Tableau de bord", backToDashboard: "← Tableau de bord",
    allGood: "Tout va bien. Tes agents sont surveillés.",
    pendingOne: "action attend ta validation.", pendingMany: "actions attendent ta validation.",
    frozen: "Incident, tes agents sont gelés.", silent: "Attention, un agent ne répond plus.",
    capReached: "Plafond de dépense atteint.",
    myAgents: "Mes agents", connectAgent: "+ Connecter un agent",
    noAgent: "Aucun agent connecté.", connectFirst: "Connecte ton premier agent",
    activeRules: "Règles actives", fullLibrary: "Bibliothèque complète",
    spend: "Dépenses API & plafond", killSwitch: "Arrêt d'urgence",
    subscription: "Compte & abonnement", seeAll: "Tout voir",
    pilot: "Pilotage", users: "Utilisateurs", revenue: "MRR estimé", arr: "ARR estimé",
    paidSubs: "Abonnés payants", conversion: "Conversion", byPlan: "Répartition par forfait",
    evolution: "Évolution dans le temps", email: "Email", signedUp: "Inscrit le", plan: "Forfait",
    // Dashboard détaillé
    dashSub: "Tes agents protégés, en un coup d'œil.", howItWorks: "Comment ça marche ?",
    online: "En ligne", unreachable: "Injoignable", frozenLabel: "Gelé",
    freeze: "Geler", unfreeze: "Dégeler", del: "Supprimer",
    edit: "Modifier", agentName: "Nom de l'agent", connectedTo: "Connecté à",
    actions30d: "Actions, 30 j", interceptions: "Interceptions", monthCost: "Coût du mois",
    neverSeen: "jamais vu", ago: "il y a",
    confirmDelete: "et tout son historique ? Irréversible.", yesDelete: "Oui, supprimer", cancel: "Annuler",
    noRules: "Aucune règle active.", activateProfile: "Active un profil (Perso / Commerçant / Builder)",
    inOneClick: "en un clic.", triggers: "déclenchement", block: "Bloquer", ask: "Demander", notify: "Notifier",
    spentThisMonth: "consommé ce mois", ofCap: "% du plafond", alert: "alerte",
    perDay: "Par jour · 30 derniers jours", noSpend: "Aucune dépense enregistrée pour l'instant.",
    byAgent: "Répartition par agent", capFeature: "Plafonds de dépense",
    capDesc: ", alerte à 80 % et blocage automatique au plafond.", inProtege: "Inclus dans Protégé",
    killDesc: "Gèle instantanément tous les appels d'outils de tes agents. Prise d'effet en moins de 30 s.",
    allFine: "Tout va bien, agents actifs", agentsFrozen: "Tes agents sont gelés",
    freezeAll: "Tout geler", confirmFreeze: "Confirmer le gel",
    frozenBanner: "Agents GELÉS, toute action est refusée.", unfreezeAgents: "Dégeler mes agents",
    noEvents: "Aucun événement pour l'instant.", pendingTitle: "en attente de ta validation",
    refuse: "Refuser", allowOnce: "Autoriser une fois", seeDetail: "Voir le détail", rule: "Règle",
    currentPlan: "Plan actuel", nextDue: "Prochaine échéance", manage: "Gérer", stripePortal: "Portail Stripe",
    monthly: "Mensuel", annual: "Annuel", monthsFree: "(2 mois offerts)", yourPlan: "Ton plan",
    recommended: "Recommandé", switchTo: "Passer à", perMonth: "/mois",
    // Login
    welcomeBack: "Ravi de te revoir", protectAgent: "Protège ton agent",
    signinSub: "Connecte-toi à ta tour de contrôle.", signupSub: "Compte gratuit, aucune carte requise.",
    emailPh: "Adresse email", pwdPh: "Mot de passe", signin: "Se connecter", createAccount: "Créer mon compte",
    or: "ou", googleBtn: "Continuer avec Google",
    noAccount: "Pas encore de compte ? Créer un compte", hasAccount: "Déjà un compte ? Se connecter",
    freeNoCard: "Gratuit · sans carte ·", in3min: "protégé en 3 minutes",
    checkMail: "Compte créé. Vérifie ta boîte mail pour confirmer ton adresse, puis connecte-toi.",
    genericError: "Une erreur est survenue.", googleUnavailable: "Connexion Google indisponible.",
    // Règles
    myRules: "Tes règles", rulesSub: "En français, sans jargon. Active un profil entier ou choisis règle par règle.",
    ruleActive: "règle active", ruleLimitFree: "(plan gratuit)", unlockMore: "Débloquer plus →",
    profile: "Profil", enableAll: "Tout activer", currentPlanIs: "Plan actuel",
    profPerso: "Perso", profPersoHint: "Pour un usage personnel du quotidien",
    profShop: "Commerçant", profShopHint: "Pour protéger clients, ventes et publications",
    profBuilder: "Builder", profBuilderHint: "Pour les agents qui codent et publient",
    // Journal
    journalSub: "Chaque action sensible, en clair. Conservé", days: "jours",
    upgradeJournal: "Passe à Protégé pour 90 jours d'historique",
    fAll: "Tout", fBlocked: "Bloqué", fApprovals: "Validations", fInfo: "Infos",
    // Compte
    myAccount: "Mon compte", tabProfile: "Profil", tabBilling: "Facturation", tabPayments: "Paiements",
    tabPreferences: "Préférences", grpAccount: "Compte", grpBilling: "Facturation",
    language: "Langue", langHint: "La langue du tableau de bord et des pages.",
    notifTelegram: "Notifications Telegram", tgLinked: "Telegram relié : tu reçois les demandes de validation sur ton téléphone.",
    tgNotLinked: "Telegram non relié : tu ne reçois pas les validations en temps réel.", tgGoLink: "Relier Telegram",
    displayName: "Nom affiché", yourName: "Ton nom", save: "Enregistrer",
    emailAddr: "Adresse email", emailHint: "Un email de confirmation sera envoyé à la nouvelle adresse.", modify: "Modifier",
    password: "Mot de passe", pwdHint: "8 caractères minimum.", newPwd: "Nouveau mot de passe", change: "Changer",
    deleteAccount: "Supprimer mon compte", deleteHint: "Efface définitivement ton compte, tes agents et tout ton historique. Irréversible.",
    sure: "Sûr ?", yesDeleteAll: "Oui, tout supprimer",
    nameUpdated: "Nom mis à jour.", checkInbox: "Vérifie ta boîte mail pour confirmer.", pwdUpdated: "Mot de passe mis à jour.",
    deleteFailed: "Suppression impossible", genericErr: "Erreur",
    endsOn: "Se termine le", renewsOn: "Se renouvelle le", cancelScheduled: "(résiliation programmée).",
    goPaid: "Passer à un plan payant", manageSub: "Gérer mon abonnement",
    manageSubHint: "Moyen de paiement, factures, changement de formule via le portail sécurisé Stripe.",
    openPortal: "Ouvrir le portail de facturation", unsubscribe: "Se désabonner",
    unsubHint: "Ton accès reste actif jusqu'à la fin de la période déjà payée.",
    cancelSub: "Résilier mon abonnement", confirmCancel: "Confirmer la résiliation",
    paymentHistory: "Historique des paiements", invoicesSub: "Tes factures et reçus.",
    noPayments: "Aucun paiement pour l'instant.", date: "Date", amount: "Montant", status: "Statut", invoice: "Facture", view: "Voir",
    stPaid: "Payée", stOpen: "En attente", stVoid: "Annulée", stUncollectible: "Impayée",
    // Plans
    planFree: "Gratuit", planProtege: "Protégé", planStudio: "Studio",
  },
  en: {
    rules: "Rules", journal: "Log", account: "Account", admin: "Admin", signout: "Sign out",
    dashboard: "Dashboard", backToDashboard: "← Dashboard",
    allGood: "All clear. Your agents are being watched.",
    pendingOne: "action awaits your approval.", pendingMany: "actions await your approval.",
    frozen: "Incident: your agents are frozen.", silent: "Heads up: an agent stopped responding.",
    capReached: "Spending cap reached.",
    myAgents: "My agents", connectAgent: "+ Connect an agent",
    noAgent: "No agent connected.", connectFirst: "Connect your first agent",
    activeRules: "Active rules", fullLibrary: "Full library",
    spend: "API spend & cap", killSwitch: "Emergency stop",
    subscription: "Account & subscription", seeAll: "See all",
    pilot: "Control", users: "Users", revenue: "Est. MRR", arr: "Est. ARR",
    paidSubs: "Paying subscribers", conversion: "Conversion", byPlan: "Breakdown by plan",
    evolution: "Over time", email: "Email", signedUp: "Signed up", plan: "Plan",
    // Dashboard detail
    dashSub: "Your protected agents, at a glance.", howItWorks: "How does it work?",
    online: "Online", unreachable: "Unreachable", frozenLabel: "Frozen",
    freeze: "Freeze", unfreeze: "Unfreeze", del: "Delete",
    edit: "Edit", agentName: "Agent name", connectedTo: "Connected to",
    actions30d: "Actions, 30 d", interceptions: "Interceptions", monthCost: "Cost this month",
    neverSeen: "never seen", ago: "",
    confirmDelete: "and all its history? This cannot be undone.", yesDelete: "Yes, delete", cancel: "Cancel",
    noRules: "No active rule.", activateProfile: "Turn on a profile (Personal / Shop / Builder)",
    inOneClick: "in one click.", triggers: "trigger", block: "Block", ask: "Ask", notify: "Notify",
    spentThisMonth: "spent this month", ofCap: "% of cap", alert: "alert",
    perDay: "Per day · last 30 days", noSpend: "No spending recorded yet.",
    byAgent: "Breakdown by agent", capFeature: "Spending caps",
    capDesc: ", alert at 80% and automatic block at the cap.", inProtege: "Included in Protected",
    killDesc: "Instantly freezes every tool call from your agents. Takes effect in under 30 s.",
    allFine: "All clear, agents active", agentsFrozen: "Your agents are frozen",
    freezeAll: "Freeze everything", confirmFreeze: "Confirm freeze",
    frozenBanner: "Agents FROZEN, every action is refused.", unfreezeAgents: "Unfreeze my agents",
    noEvents: "No events yet.", pendingTitle: "awaiting your approval",
    refuse: "Refuse", allowOnce: "Allow once", seeDetail: "See detail", rule: "Rule",
    currentPlan: "Current plan", nextDue: "Next payment", manage: "Manage", stripePortal: "Stripe portal",
    monthly: "Monthly", annual: "Annual", monthsFree: "(2 months free)", yourPlan: "Your plan",
    recommended: "Recommended", switchTo: "Switch to", perMonth: "/mo",
    // Login
    welcomeBack: "Welcome back", protectAgent: "Protect your agent",
    signinSub: "Sign in to your control room.", signupSub: "Free account, no card required.",
    emailPh: "Email address", pwdPh: "Password", signin: "Sign in", createAccount: "Create my account",
    or: "or", googleBtn: "Continue with Google",
    noAccount: "No account yet? Create one", hasAccount: "Already have an account? Sign in",
    freeNoCard: "Free · no card ·", in3min: "protected in 3 minutes",
    checkMail: "Account created. Check your inbox to confirm your address, then sign in.",
    genericError: "Something went wrong.", googleUnavailable: "Google sign-in unavailable.",
    // Rules
    myRules: "Your rules", rulesSub: "Plain words, no jargon. Turn on a whole profile or pick rule by rule.",
    ruleActive: "active rule", ruleLimitFree: "(free plan)", unlockMore: "Unlock more →",
    profile: "Profile", enableAll: "Enable all", currentPlanIs: "Current plan",
    profPerso: "Personal", profPersoHint: "For everyday personal use",
    profShop: "Shop", profShopHint: "To protect clients, sales and posts",
    profBuilder: "Builder", profBuilderHint: "For agents that code and ship",
    // Log
    journalSub: "Every sensitive action, in plain words. Kept", days: "days",
    upgradeJournal: "Go Protected for 90 days of history",
    fAll: "All", fBlocked: "Blocked", fApprovals: "Approvals", fInfo: "Info",
    // Account
    myAccount: "My account", tabProfile: "Profile", tabBilling: "Billing", tabPayments: "Payments",
    tabPreferences: "Preferences", grpAccount: "Account", grpBilling: "Billing",
    language: "Language", langHint: "The language of the dashboard and pages.",
    notifTelegram: "Telegram notifications", tgLinked: "Telegram linked: approval requests reach your phone.",
    tgNotLinked: "Telegram not linked: you are not receiving real-time approvals.", tgGoLink: "Link Telegram",
    displayName: "Display name", yourName: "Your name", save: "Save",
    emailAddr: "Email address", emailHint: "A confirmation email will be sent to the new address.", modify: "Change",
    password: "Password", pwdHint: "8 characters minimum.", newPwd: "New password", change: "Change",
    deleteAccount: "Delete my account", deleteHint: "Permanently erases your account, your agents and all your history. This cannot be undone.",
    sure: "Sure?", yesDeleteAll: "Yes, delete everything",
    nameUpdated: "Name updated.", checkInbox: "Check your inbox to confirm.", pwdUpdated: "Password updated.",
    deleteFailed: "Deletion failed", genericErr: "Error",
    endsOn: "Ends on", renewsOn: "Renews on", cancelScheduled: "(cancellation scheduled).",
    goPaid: "Move to a paid plan", manageSub: "Manage my subscription",
    manageSubHint: "Payment method, invoices, plan changes through the secure Stripe portal.",
    openPortal: "Open the billing portal", unsubscribe: "Unsubscribe",
    unsubHint: "Your access stays active until the end of the period you already paid for.",
    cancelSub: "Cancel my subscription", confirmCancel: "Confirm cancellation",
    paymentHistory: "Payment history", invoicesSub: "Your invoices and receipts.",
    noPayments: "No payment yet.", date: "Date", amount: "Amount", status: "Status", invoice: "Invoice", view: "View",
    stPaid: "Paid", stOpen: "Pending", stVoid: "Void", stUncollectible: "Uncollectible",
    // Plans
    planFree: "Free", planProtege: "Protected", planStudio: "Studio",
  },
} as const;
